[project]
name = "flaskapp"
version = "1.0.0"
description = "planetracker thing"
dependencies = [
    "flask",
    "requests"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"